workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.numelodic.musicapp"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform
        script: |
          # Set deployment target environment variable
          export IPHONEOS_DEPLOYMENT_TARGET=16.0
          
          # Add iOS platform (ignore pod install errors during add)
          npx cap add ios 2>&1 || true
          
          # Fix deployment target in Podfile  
          cd ios/App
          sed -i '' "s/platform :ios, '.*'/platform :ios, '16.0'/" Podfile
          cat Podfile
          
          # Fix deployment target in Xcode project
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g' {} \;
          
          # Remove Pods directory to force clean install
          rm -rf Pods Podfile.lock
          
          # Copy web assets
          cd ../..
          npx cap copy ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install --repo-update
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Write API key file
        script: |
          # Write the private key to a file (handles newline issues)
          mkdir -p ~/.appstoreconnect/private_keys
          printf '%s\n' "$APP_STORE_CONNECT_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
          # Debug: show key file exists and has content
          ls -la ~/.appstoreconnect/private_keys/
          head -1 ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
      
      - name: Generate certificate key
        script: |
          # Generate RSA key for certificate creation
          ssh-keygen -t rsa -b 2048 -m PEM -f ~/.appstoreconnect/cert_key.pem -N ""
          
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key ~/.appstoreconnect/cert_key.pem \
            --create
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
