workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.numelodic.musicapp"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform
        script: |
          # Set deployment target environment variable
          export IPHONEOS_DEPLOYMENT_TARGET=16.0
          
          # Add iOS platform (ignore pod install errors during add)
          npx cap add ios 2>&1 || true
          
          # Fix deployment target in Podfile  
          cd ios/App
          sed -i '' "s/platform :ios, '.*'/platform :ios, '16.0'/" Podfile
          cat Podfile
          
          # Fix deployment target in Xcode project
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g' {} \;
          
          # Remove Pods directory to force clean install
          rm -rf Pods Podfile.lock
          
          # Copy web assets
          cd ../..
          npx cap copy ios
      
      - name: Set app icon
        script: |
          # Copy the 1024x1024 app icon into the iOS asset catalog
          ICON_SET="ios/App/App/Assets.xcassets/AppIcon.appiconset"
          
          # Copy icon as the single 1024x1024 icon (iOS 17+ uses single size)
          cp ios-app-icon.png "$ICON_SET/AppIcon-1024x1024@1x.png"
          
          # Generate all required icon sizes for older iOS versions
          SIZES="20 29 40 58 60 76 80 87 120 152 167 180 1024"
          for SIZE in $SIZES; do
            sips -z $SIZE $SIZE ios-app-icon.png --out "$ICON_SET/AppIcon-${SIZE}x${SIZE}.png" 2>/dev/null || true
          done
          
          # Write the Contents.json for the asset catalog
          cat > "$ICON_SET/Contents.json" << 'ICONJSON'
          {
            "images" : [
              {
                "filename" : "AppIcon-40x40.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "20x20",
                "scale" : "2x"
              },
              {
                "filename" : "AppIcon-60x60.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "20x20",
                "scale" : "3x"
              },
              {
                "filename" : "AppIcon-58x58.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "29x29",
                "scale" : "2x"
              },
              {
                "filename" : "AppIcon-87x87.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "29x29",
                "scale" : "3x"
              },
              {
                "filename" : "AppIcon-80x80.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "40x40",
                "scale" : "2x"
              },
              {
                "filename" : "AppIcon-120x120.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "40x40",
                "scale" : "3x"
              },
              {
                "filename" : "AppIcon-120x120.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "60x60",
                "scale" : "2x"
              },
              {
                "filename" : "AppIcon-180x180.png",
                "idiom" : "universal",
                "platform" : "ios",
                "size" : "60x60",
                "scale" : "3x"
              },
              {
                "filename" : "AppIcon-76x76.png",
                "idiom" : "ipad",
                "platform" : "ios",
                "size" : "76x76",
                "scale" : "1x"
              },
              {
                "filename" : "AppIcon-152x152.png",
                "idiom" : "ipad",
                "platform" : "ios",
                "size" : "76x76",
                "scale" : "2x"
              },
              {
                "filename" : "AppIcon-167x167.png",
                "idiom" : "ipad",
                "platform" : "ios",
                "size" : "83.5x83.5",
                "scale" : "2x"
              },
              {
                "filename" : "AppIcon-1024x1024.png",
                "idiom" : "ios-marketing",
                "platform" : "ios",
                "size" : "1024x1024",
                "scale" : "1x"
              }
            ],
            "info" : {
              "author" : "xcode",
              "version" : 1
            }
          }
          ICONJSON
          
          # Also copy as the main 1024 icon
          cp ios-app-icon.png "$ICON_SET/AppIcon-1024x1024.png"
          
          echo "App icon set up successfully"
          ls -la "$ICON_SET/"
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install --repo-update
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Write API key file
        script: |
          # Write the private key to a file (handles newline issues)
          mkdir -p ~/.appstoreconnect/private_keys
          printf '%s\n' "$APP_STORE_CONNECT_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
          # Debug: show key file exists and has content
          ls -la ~/.appstoreconnect/private_keys/
          head -1 ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
      
      - name: Generate certificate key
        script: |
          # Generate RSA private key in PEM format for certificate creation
          openssl genrsa -out ~/.appstoreconnect/cert_key.pem 2048
          
      - name: Revoke old certificates
        script: |
          app-store-connect list-certificates \
            --type DISTRIBUTION IOS_DISTRIBUTION \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --json 2>/dev/null | python3 -c "
          import sys, json
          try:
              certs = json.load(sys.stdin)
              for cert in certs:
                  print(cert.get('id', ''))
          except:
              pass
          " | while read cert_id; do
            if [ -n "$cert_id" ]; then
              echo "Revoking certificate: $cert_id"
              app-store-connect delete-certificate "$cert_id" \
                --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
                --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
                --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" 2>&1 || true
            fi
          done
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "@file:$HOME/.appstoreconnect/cert_key.pem" \
            --create
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
