workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.numelodic.musicapp"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform
        script: |
          # Create ios directory structure first
          mkdir -p ios/App
          
          # Create Podfile with correct deployment target
          cat > ios/App/Podfile << 'EOF'
          require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
          
          platform :ios, '14.0'
          use_frameworks!
          
          install! 'cocoapods', :disable_input_output_paths => true
          
          def capacitor_pods
            pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
            pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
          end
          
          target 'App' do
            capacitor_pods
          end
          EOF
          
          # Now add iOS platform
          npx cap add ios || true
          npx cap sync ios --deployment || true
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install --repo-update
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
